language: python
python:
  - 2.7
sudo: false
install:
  - pip install jinja2
script:
  - "build/build && if [ $TRAVIS_BRANCH = master ] && [ $TRAVIS_PULL_REQUEST = false ]; then build/upload; fi"
notifications:
  email:
    - remirampin@gmail.com
